version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "4300:4300"
      - "5000:5000"
    links:
      - redis
      - mongo
    environment:
      - PORT=5000
      - QUEUE_NAME=scratch
      - DB_HOST=mongodb://mongo:27017/scratch
      - REDIS_HOST=redis
  mongo:
    container_name: app-mongo
    image: "mongo:latest"
  redis:
    container_name: app-redis
    image: "redis:latest"
